name: "Lint PR title"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          headerPattern: '^([\w/]+)(?:\(([\w\$\.\-\* ]*)\))?\: (.*)$'
          types: |
            BREAKING
            unstable/BREAKING
            deprecation
            unstable/deprecation
            feat
            unstable/feat
            fix
            unstable/fix
            docs
            unstable/docs
            refactor
            unstable/refactor
            perf
            unstable/perf
            test
            unstable/test
            ci
            chore
            revert
          # This should be kept up-to-date with the current packages list
          scopes: |
            archive(/unstable)?
            assert(/unstable)?
            async(/unstable)?
            bytes(/unstable)?
            cache(/unstable)?
            cli(/unstable)?
            collections(/unstable)?
            crypto(/unstable)?
            csv(/unstable)?
            data-structures(/unstable)?
            datetime(/unstable)?
            dotenv(/unstable)?
            encoding(/unstable)?
            expect(/unstable)?
            fmt(/unstable)?
            front-matter(/unstable)?
            fs(/unstable)?
            html(/unstable)?
            http(/unstable)?
            ini(/unstable)?
            internal
            io(/unstable)?
            json(/unstable)?
            jsonc(/unstable)?
            log(/unstable)?
            media-types(/unstable)?
            msgpack(/unstable)?
            net(/unstable)?
            path(/unstable)?
            regexp(/unstable)?
            semver(/unstable)?
            streams(/unstable)?
            testing(/unstable)?
            text(/unstable)?
            toml(/unstable)?
            ulid(/unstable)?
            url(/unstable)?
            uuid(/unstable)?
            webgpu(/unstable)?
            yaml(/unstable)?
